# Generated by scripts/release.py prepare; update from verified release archives.
class Aviary < Formula
  desc "Bird-compatible CLI for reading and posting on X"
  homepage "https://github.com/grahamannett/aviary-swift"
  version "0.1.2"

  on_macos do
    depends_on macos: :ventura
    on_arm do
      url "https://github.com/grahamannett/aviary-swift/releases/download/v0.1.2/aviary-0.1.2-macos-arm64.tar.gz"
      sha256 "d9180a8efbdb3c1fa2351fda7eee32fef07ec218a6c025d82cc10a7a8f164ea9"
    end
    on_intel do
      url "https://github.com/grahamannett/aviary-swift/releases/download/v0.1.2/aviary-0.1.2-macos-x86_64.tar.gz"
      sha256 "ca04c96a4f987e76626734f3d734d7c8f0188d1cf7e25fb74a42250d1f18b938"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahamannett/aviary-swift/releases/download/v0.1.2/aviary-0.1.2-linux-arm64.tar.gz"
      sha256 "e76f29509f16ed71b95d7f8767567eb694bbdadba8f100bcccb53d12018f8a5c"
    end
    on_intel do
      url "https://github.com/grahamannett/aviary-swift/releases/download/v0.1.2/aviary-0.1.2-linux-x86_64.tar.gz"
      sha256 "7382424a2a8dcc953a7e19d645f2e0a087b49ef4a1884c5aae13fab16f0e210f"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/aviary"
  end

  test do
    ENV["AVIARY_SKIP_QUERY_ID_REFRESH"] = "1"
    ENV["XDG_CONFIG_HOME"] = (testpath/"config").to_s
    assert_match "whoami", shell_output("#{bin}/aviary --help")
    assert_match "ok ", shell_output("#{libexec}/libexec/aviary-selftest --resources-only")
    assert_match '"features"', shell_output("#{bin}/aviary query-ids --json")
  end
end
