# Generated by scripts/release.py prepare; update from verified release archives.
class Aviary < Formula
  desc "Bird-compatible CLI for reading and posting on X"
  homepage "https://github.com/grahamannett/aviary-swift"
  version "0.1.1"

  on_macos do
    depends_on macos: :ventura
    on_arm do
      url "https://github.com/grahamannett/aviary-swift/releases/download/v0.1.1/aviary-0.1.1-macos-arm64.tar.gz"
      sha256 "7cd77a127bf938d7bc229306b12b993bc98aa09a3d5f5922b94cc6e901ad7a19"
    end
    on_intel do
      url "https://github.com/grahamannett/aviary-swift/releases/download/v0.1.1/aviary-0.1.1-macos-x86_64.tar.gz"
      sha256 "ad72a48f26a3650e5c7f77ce0f7f6e5040c688622808527c8b2a9074ea1a63ed"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahamannett/aviary-swift/releases/download/v0.1.1/aviary-0.1.1-linux-arm64.tar.gz"
      sha256 "340bcf08fadf9385445d513ac8cff28761a02c38e16a025338dd0af9ab5f3df6"
    end
    on_intel do
      url "https://github.com/grahamannett/aviary-swift/releases/download/v0.1.1/aviary-0.1.1-linux-x86_64.tar.gz"
      sha256 "7943435acee1c6a3ec0fa111cdecd27c24afb44f81f699ca9cbaa01401c46562"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/aviary"
  end

  test do
    ENV["AVIARY_SKIP_QUERY_ID_REFRESH"] = "1"
    ENV["XDG_CONFIG_HOME"] = (testpath/"config").to_s
    assert_match "whoami", shell_output("#{bin}/aviary --help")
    assert_match "ok ", shell_output("#{libexec}/libexec/aviary-selftest --resources-only")
    assert_match '"features"', shell_output("#{bin}/aviary query-ids --json")
  end
end
