# Generated by scripts/release.py prepare; update from verified release archives.
class Aviary < Formula
  desc "Bird-compatible CLI for reading and posting on X"
  homepage "https://github.com/grahamannett/aviary-swift"
  version "0.1.0"

  on_macos do
    depends_on macos: :ventura
    on_arm do
      url "https://github.com/grahamannett/aviary-swift/releases/download/v0.1.0/aviary-0.1.0-macos-arm64.tar.gz"
      sha256 "c9f9faef91339ba4f3eb56cca4dde5be13fa81708216c42fb0db66f253412668"
    end
    on_intel do
      url "https://github.com/grahamannett/aviary-swift/releases/download/v0.1.0/aviary-0.1.0-macos-x86_64.tar.gz"
      sha256 "644a6a2a6f595a1c25ec2f17ff095ce73ac18598f60f7f6cff152a6e77744d93"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahamannett/aviary-swift/releases/download/v0.1.0/aviary-0.1.0-linux-arm64.tar.gz"
      sha256 "f205c44193b4cba3b31e275b654171735f9b8d6c9998d3b092a39c320f93ed75"
    end
    on_intel do
      url "https://github.com/grahamannett/aviary-swift/releases/download/v0.1.0/aviary-0.1.0-linux-x86_64.tar.gz"
      sha256 "2088b4184cdae07910fa425febcdac1fba40d8594001362194f90f5a0734958b"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bin/aviary"
  end

  test do
    ENV["AVIARY_SKIP_QUERY_ID_REFRESH"] = "1"
    ENV["XDG_CONFIG_HOME"] = (testpath/"config").to_s
    assert_match "whoami", shell_output("#{bin}/aviary --help")
    assert_match "ok ", shell_output("#{libexec}/libexec/aviary-selftest --resources-only")
    assert_match '"features"', shell_output("#{bin}/aviary query-ids --json")
  end
end
